FROM ubuntu:cloudbuild_cache

SHELL ["/bin/bash", "-c"]
ENTRYPOINT ["/bin/bash"]

RUN apt-get -q update \
 && apt-get -y --no-install-recommends --fix-broken install \
      coreutils dpkg squashfs-tools \
 && find /var -name '*-old' -type f -delete \
 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
